# Generated by Django 5.1.4 on 2025-12-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('appid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('icon_url', models.URLField(blank=True)),
                ('genre', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('steamid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('personaname', models.CharField(max_length=255)),
                ('avatar_url', models.CharField(max_length=255)),
            ],
        ),
    ]
