# Generated by Django 5.1.4 on 2026-01-07 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_profile_open',
        ),
    ]
