# Generated by Django 5.1.4 on 2026-01-09 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_users_is_profile_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userachievement',
            name='achievement',
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userachievement',
            name='user',
        ),
        migrations.RemoveField(
            model_name='game',
            name='genre',
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
        migrations.DeleteModel(
            name='UserAchievement',
        ),
    ]
